import type { Metadata } from "next";
import "./globals.css";
import { Footer, Navbar, ThemeProvider } from "@/components";

export const metadata: Metadata = {
  title: "X-Meta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider> 
      </body>
    </html>
  );
}
